// Export utilities for analysis results

export function copy7DayPlan(plan) {
  const text = plan.map(day => 
    `DAY ${day.day}: ${day.title}\n${day.tasks.map(task => `  • ${task}`).join('\n')}`
  ).join('\n\n')
  
  navigator.clipboard.writeText(text)
}

export function copyChecklist(checklist) {
  const text = Object.values(checklist).map(round =>
    `${round.title}\n${round.items.map(item => `  ☐ ${item}`).join('\n')}`
  ).join('\n\n')
  
  navigator.clipboard.writeText(text)
}

export function copyQuestions(questions) {
  const text = questions.map((q, idx) => `${idx + 1}. ${q}`).join('\n\n')
  navigator.clipboard.writeText(text)
}

export function downloadAsTxt(analysis) {
  const content = `
PLACEMENT PREPARATION ANALYSIS
${analysis.company || 'Company'} - ${analysis.role || 'Role'}
Analyzed: ${new Date(analysis.createdAt).toLocaleString()}
Readiness Score: ${analysis.currentReadinessScore || analysis.readinessScore}/100

═══════════════════════════════════════════════════════════

KEY SKILLS EXTRACTED
${Object.entries(analysis.extractedSkills).map(([key, category]) => 
  `\n${category.name}:\n${category.skills.map(s => `  • ${s}`).join('\n')}`
).join('\n')}

═══════════════════════════════════════════════════════════

ROUND-WISE PREPARATION CHECKLIST
${Object.values(analysis.checklist).map(round =>
  `\n${round.title}\n${round.items.map(item => `  ☐ ${item}`).join('\n')}`
).join('\n')}

═══════════════════════════════════════════════════════════

7-DAY PREPARATION PLAN
${analysis.plan.map(day => 
  `\nDAY ${day.day}: ${day.title}\n${day.tasks.map(task => `  • ${task}`).join('\n')}`
).join('\n')}

═══════════════════════════════════════════════════════════

10 LIKELY INTERVIEW QUESTIONS
${analysis.questions.map((q, idx) => `\n${idx + 1}. ${q}`).join('\n')}

═══════════════════════════════════════════════════════════
Generated by Placement Readiness Platform
`.trim()

  const blob = new Blob([content], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${analysis.company || 'Analysis'}_${analysis.role || 'Prep'}_${Date.now()}.txt`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
